services:
  - type: web
    name: app
    env: docker
    buildCommand: ./path/to/your/docker-build-script
    startCommand: ./path/to/your/docker-start-script
    image: jc21/nginx-proxy-manager:latest
    envVars:
      - key: VIRTUAL_PORT
        value: '80'
      - key: VIRTUAL_HOST
        value: 'your-render-subdomain.onrender.com'
    ports:
      - number: 80
      - number: 81
      - number: 443
    volumes:
      - name: data
        path: /data
      - name: letsencrypt
        path: /etc/letsencrypt
